### ISSUE TITLE
Is it possible to turn that into Homebridge npm?

### ISSUE THREAD

**Issue by bleedr** [kquinsland/JACKYLED-BLE-RGB-LED-Strip-controller#2]
Hi Karl,
Spending the whole day playing around with my LED stand based on strips, I finally found your GitHub after following
https://github.com/arduino12/ble_rgb_led_strip_controller

It is using exactly the same codes that my LED stand is using.
Now I’m curious after looking at your skills, if it would be possible to put that into Homebridge npm? This would help a lot of people.

Thanks & Greetings!

**Comment by kquinsland** [comment]
Good question. Short answer is: probably.

I don't use HomeBridge so i'm not clear on most of the details but it does look like there's a few existing implementations out there that are close. In particular, this project is rather new  and the targeted hardware is pretty similar to the JACKYLED controller.

https://github.com/stoner221/homebridge-led-strip-ble


I think your best bet is to open an Issue on that repo or contact the author and ask them to implement support for the JACKYLED controller. I never bothered to reverse engineer all the advanced functions that the controller supports, but the packets needed to send RGB values are pretty simple and covered [here](https://github.com/kquinsland/JACKYLED-BLE-RGB-LED-Strip-controller#what-i-found).

And the characteristic UUIDs that worked are [here](https://github.com/kquinsland/JACKYLED-BLE-RGB-LED-Strip-controller/blob/eedab0ea5a9666ceb58de27784a9fed1a964570c/files/src/main/java/com/karlquinsland/android/btleled/SampleGattAttributes.java#L34):

```java
    // the UUIDs that seem to work for my controller
    // TODO: add support for others?
    public static String CLIENT_SERVICE_STRIP = "0000ffe0-0000-1000-8000-00805f9b34fb";
    public static String CLIENT_CHARACTERISTIC_COLOR = "0000ffe1-0000-1000-8000-00805f9b34fb";
```

I wrote most of code / did the reverse engineering about a year before publishing this so it's been a _while_ and my memory is fuzzy. I don't remember the exact order of operations, but i think the meat of it all is in [`setupStrandOutputToggle`](https://github.com/kquinsland/JACKYLED-BLE-RGB-LED-Strip-controller/blob/eedab0ea5a9666ceb58de27784a9fed1a964570c/files/src/main/java/com/karlquinsland/android/btleled/DeviceControlActivity.java#L546
) and [`sendRGBAndBrightness`](https://github.com/kquinsland/JACKYLED-BLE-RGB-LED-Strip-controller/blob/eedab0ea5a9666ceb58de27784a9fed1a964570c/files/src/main/java/com/karlquinsland/android/btleled/DeviceControlActivity.java#L571)


The actual code that takes a simple r/g/b value or briightness value and encodes it into bytes that the controller will understand is in the [`ControllerDriverClass`](https://github.com/kquinsland/JACKYLED-BLE-RGB-LED-Strip-controller/blob/eedab0ea5a9666ceb58de27784a9fed1a964570c/files/src/main/java/com/karlquinsland/android/btleled/ControllerDriverClass.java#L158).

Good luck!
